version: '3.8'

services:
  db:
    user: root
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - "1433:1433"
    environment:
      - MSSQL_SA_PASSWORD=admin123A
      - MSSQL_PID=Express
      - ACCEPT_EULA=Y
